// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckIngredientsController from "./check_ingredients_controller"
application.register("check-ingredients", CheckIngredientsController)

import CuisineHistoryController from "./cuisine_history_controller"
application.register("cuisine-history", CuisineHistoryController)

import CuisineReviewsController from "./cuisine_reviews_controller"
application.register("cuisine-reviews", CuisineReviewsController)

import DishCardController from "./dish_card_controller"
application.register("dish-card", DishCardController)

import DisplayTabController from "./display_tab_controller"
application.register("display-tab", DisplayTabController)

import GlobeFilteringController from "./globe_filtering_controller"
application.register("globe-filtering", GlobeFilteringController)

import HeartController from "./heart_controller"
application.register("heart", HeartController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HomeNavBtnController from "./home_nav_btn_controller"
application.register("home-nav-btn", HomeNavBtnController)

import MapController from "./map_controller"
application.register("map", MapController)

import MusicPlayerController from "./music_player_controller"
application.register("music-player", MusicPlayerController)

import ReviewFavController from "./review_fav_controller"
application.register("review-fav", ReviewFavController)

import ReviewFavLoginController from "./review_fav_login_controller"
application.register("review-fav-login", ReviewFavLoginController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import StopwatchController from "./stopwatch_controller"
application.register("stopwatch", StopwatchController)
